### ISSUE TITLE
Avaliação da primeira etapa

### ISSUE THREAD

**Issue by santos-fernando** [Adroan/MSNReborn-Projeto#1]
EQUIPE		NOTA: 1.4 (nota máxima da etapa: 1.5)
	Adroan
	Vinicius

ALOCAÇÃO DAS TAREFAS
Ok.

DIAGRAMA DE SEQUÊNCIA DEFINITIVO PROTOCOLO CLIENTE/SERVIDOR
Ok.

DIAGRAMA DE CLASSE SERVIDOR
Não está especificado como serão armazenados os contados de um Cliente. Seria importante que neste diagrama, ao menos na classe de modelo, estivessem especificados os atributos.

DIAGRAMA DE SEQUÊNCIA PRELIMINAR CLIENTE/CLIENTE
* Sugestão: não há a necessidade de ter um retorno de "confirmação de recebimento", pois ao usar o protocolo TCP, a entrega/recebimento é garantido.

**Comment by Adroan** [comment]
Professor, 
A classe de modelo esta na estruturação do pacote, esta em diagrama de classes/src/model porém acabei não colocando ela no diagrama de controle

**Comment by santos-fernando** [comment]
Oi,
Eu encontrei a classe. Porém, ela está vazia (sem atributos). Era isso que eu me referia na avaliação anterior. É para vocês pensarem em quais dados vão ser necessários persistir de cada Cliente, levando em consideração todos os requisitos.  Favor ajustar o diagrama, fazer push, e atualizar esta issue quando foi feito para eu fazer nova avaliação e atualizar a nota.

**Comment by Adroan** [comment]
Olá,
Realizei a atualização da Model Contato

**Comment by santos-fernando** [comment]
EQUIPE		NOTA FINAL: 1.5 (nota máxima da etapa: 1.5)
	Adroan
	Vinicius
DIAGRAMA DE CLASSE SERVIDOR
**[Revisão de 2019-11-11]** Ok.
